rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('faq/', views.faq, name='faq'),
    path('category/<slug:category_name_slug>/',
        views.show_category, name='show_category'),
    path('category/<slug:category_name_slug>/add_page/',
        views.add_page, name='add_page'),
    path('add_category/', views.add_category, name='add_category')
    

]

tango_with_django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    # The above maps any URLs starting with rango/ to be handled by rango.
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.template.defaultfilters import slugify
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'pages'
    def __str__(self):
        return self.title
        

rango/forms.py
from django import forms
from rango.models import Page, Category

class CategoryForm(forms.ModelForm):
    name = forms.CharField(
        max_length=Category._meta.get_field('name').max_length,
        help_text="Please enter the category name."
    )
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(
        max_length=Page._meta.get_field('title').max_length,
        help_text="Please enter the title of the page."
    )
    url = forms.URLField(
        max_length=Page._meta.get_field('url').max_length,
        help_text="Please enter the URL of the page."
    )
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values; we may not want to include them.
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,
        exclude = ('category',)
        # or specify the fields to include (don't include the category field).
        #fields = ('title', 'url', 'views')

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        # If url is not empty and doesn't start with 'http://',
        # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url

        return cleaned_data

rango/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.urls import reverse

from django.http import HttpResponse

from rango.models import Category, Page
from rango.forms import CategoryForm
from rango.forms import PageForm

def index(request):
    # Query the database for a list of ALL categories currently stored.
    # Order the categories by the number of likes in descending order.
    # Retrieve the top 5 only -- or all if less than 5.
    # Place the list in our context_dict dictionary (with our boldmessage!)
    # that will be passed to the template engine.
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list
    # Render the response and send it back!
    return render(request, 'rango/index.html', context=context_dict)


def about(request):
    # prints out whether the method is a GET or a POST
    print(request.method)
    # prints out the user name, if no one is logged in it prints `AnonymousUser`
    print(request.user)
    return render(request, 'rango/about.html', {})


def faq(request):
    faq_list = [
        {"question": "What is Django?", "answer": "Django is a high-level Python web framework that helps in app development."},
    ]
    # Construct a dictionary for the context to pass to the template
    context_dict = {
        'faq_list': faq_list,
    }
    return render(request, 'rango/faq.html', context=context_dict)

# Create your views here.
def show_category(request, category_name_slug):
    # Create a context dictionary which we can pass
    # to the template rendering engine.
    context_dict = {}
    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # The .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)
        # Retrieve all of the associated pages.
        # The filter() will return a list of page objects or an empty list.
        pages = Page.objects.filter(category=category)
        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from
        # the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything -
        # the template will display the "no category" message for us.
        context_dict['category'] = None
        context_dict['pages'] = None
    # Go render the response and return it to the client.
    return render(request, 'rango/category.html', context=context_dict)

def add_category(request):
    form = CategoryForm()
    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)
    # Have we been provided with a valid form?
    if form.is_valid():
        # Save the new category to the database.
        form.save(commit=True)
        # Now that the category is saved, we could confirm this.
        # For now, just redirect the user back to the index view.
        return redirect('/rango/')
    else:
        # The supplied form contained errors -
        # just print them to the terminal.
        print(form.errors)
    # Will handle the bad form, new form, or no form supplied cases.
    # Render the form with error messages (if any).
    return render(request, 'rango/add_category.html', {'form': form})

    from rango.forms import PageForm

def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
        # You cannot add a page to a Category that does not exist...
    if category is None:
        return redirect('/rango/')

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return redirect(reverse('rango:show_category',
                                        kwargs={'category_name_slug':
                                                category_name_slug}))
    else:
        print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About Rango
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        here is the about page. <br />
        <strong>This tutorial has been put together by KFC.</strong><br />
    </div>
    <div>
        <img src="{%static 'images/rango.jpg' %}" alt="Picture of Rango" /> <!-- New line -->
    </div>
    <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat." />
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}
    <h1>Add a Category</h1>
    <div>
    <form id="category_form" method="post" action="/rango/add_category/">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Create Category" />
    </form>
    </div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Page
{% endblock %}

{% block body_block %}
    <h1>Add a Page</h1>
    <div>
    <form id="add_page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Create Page" />
    </form>
    </div>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html>
    <head>
        <title>
            Rango -
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
        {% block body_block %}
        {% endblock %}
        </div>
        
        <div>
            {% block sidebar_block %}
            {% get_category_list %}
            {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
                <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></l\i>
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div>
    </body>
</html>

templates/rango/categories.html
<ul>
{% if categories %}
    {% for c in categories %}
        {% if c == current_category %}
        <li>
        <strong>
                <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
        </strong>
        </li>
        {% else %}
        <li>
                <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
        </li>
        {% endif %}
    {% endfor %}
{% else %}
    <li><strong>There are no categories present.</strong></li>
{% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
    <h1>{{ category.name }}</h1>
    {% if pages %}
    <ul>
        {% for page in pages %}
        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <strong>No pages currently in category.</strong><br/>
    {% endif %}

    <a href="{% url 'rango:add_page' category.slug %}">Add a New Page</a> <br />
    {% else %}
    The specified category does not exist.
    {% endif %}
{% endblock %}

templates/rango/faq.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    FAQ
{% endblock %}

{% block body_block %}
    <h1>Frequently Asked Questions</h1>   
    <ul>
        {% for faq in faq_list %}
            <li>
                <strong>{{ faq.question }}</strong>
                <p>{{ faq.answer }}</p>
            </li>
        {% endfor %}
    </ul>
    <a href="/rango/">Index</a>
    <div>
        <img src="{% static 'images/faq.jpg' %}"
            alt="Picture of FAQ" /> <!-- New line -->
    </div>
{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Homepage
{% endblock %}

{% block body_block %}
<h1>Rango says...</h1>
<div>
    hey there partner! <br />
    <strong>{{ boldmessage }}</strong><br />
</div>

<div>
    <h2>Most Liked Categories</h2>
    {% if categories %}
        <ul>
            {% for category in categories %}
            <li><a href="/rango/category/{{ category.slug }}/">{{ category.name }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <strong>There are no categories present.</strong>
    {% endif %}
</div>

<div>
    <h2>Most Viewed Pages</h2> 
    {% if pages %}
        <ul>
        {% for page in pages|slice:":5" %}
            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <strong>There are no pages present.</strong>
    {% endif %}
</div>

<div>
    <img src="{% static "images/rango.jpg" %}"
        alt="Picture of Rango" />
</div>
{% endblock %}












<!DOCTYPE html>
{% load staticfiles %} <!-- New line -->
<html>
    <head>
        <title>Rango</title>
    </head>
    <body>
        <h1>Rango says...</h1>
        <div>
            hey there partner! <br />
            <strong>{{ boldmessage }}</strong><br />
        </div>

        <div>
            <h2>Most Liked Categories</h2>
            {% if categories %}
                <ul>
                    {% for category in categories %}
                    <li><a href="/rango/category/{{ category.slug }}/">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>There are no categories present.</strong>
            {% endif %}
        </div>

        <div>
            <h2>Most Viewed Pages</h2> 
            {% if pages %}
                <ul>
                {% for page in pages|slice:":5" %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
                </ul>
            {% else %}
                <strong>There are no pages present.</strong>
            {% endif %}
        </div>
        
        <div>
            <a href="/rango/about/">About</a><br />
            <a href="/rango/add_category/">Add a New Category</a><br />
            <img src="{% static "images/rango.jpg" %}"
                alt="Picture of Rango" />
        </div>
    </body>

</html>
            